# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox,QApplication
import g4f
import sys
import keyboard

class Ai(QtCore.QThread):
    prompt_signal = QtCore.pyqtSignal(str)
    output_set_signal = QtCore.pyqtSignal(str)

    prompt = ''
    output = ''

    def __init__(self):
        super().__init__()

        self.prompt_signal.connect(self.ai_setup)
    def ai_setup(self, prompt):
        self.prompt = prompt
    def run(self):
        try:
            user_input = self.prompt


            response_text = ""
            chunk_size = 700
            chunks = [user_input[i:i + chunk_size] for i in range(0, len(user_input), chunk_size)]

            for chunk in chunks:
                response = g4f.ChatCompletion.create(
                    model='gpt-3.5-turbo',
                    messages=[{'role': 'user', 'content': chunk}],
                    stream=True
                )
                for event in response:
                    self.output = self.output + event
                self.output += '\n\n'
                self.output_set_signal.emit(self.output)

            # translator = Translator() #Translatepy не используется в данном коде
            # translated_text = translator.translate(response_text, target='ru') #Translatepy не используется в данном коде
            # self.textEdit_3.setText(translated_text)

        except Exception as e:
            QMessageBox.critical(self.centralwidget, "Ошибка", f"Произошла ошибка: {e}")
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.response = ''
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 361)
        MainWindow.setWindowIcon(QtGui.QIcon('ico.jpg'))
        self.m_window = MainWindow
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(721, 362))
        MainWindow.setStyleSheet("background-color: rgb(42, 42, 42);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 300, 561, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.textEdit.setObjectName("textEdit")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(580, 300, 131, 51))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(20, 179, 141);\n"
"    border-radius: 10px;\n"
"    border-color: rgb(15, 139, 108);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(15, 139, 108);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(11, 106, 82);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.connectInput)
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 10, 701, 221))
        self.textEdit_2.setStyleSheet("background-color: rgb(172, 172, 172);\n"
"color: rgb(0, 0, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(10, 240, 701, 51))
        self.textEdit_3.setStyleSheet("background-color: rgb(134, 134, 134);\n"
"\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.textEdit_3.setObjectName("textEdit_3")

        self.ai_thread = Ai()
        self.ai_thread.output_set_signal.connect(self.setOutput)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PyGPT"))
        self.pushButton_2.setText(_translate("MainWindow", "Отправить"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
    def setOutput(self, value):
        self.textEdit_2.setText(value)
        self.m_window.setWindowTitle('PyGPT')
    def connectInput(self):
        prompt = self.textEdit.toPlainText()
        self.textEdit_3.setText(prompt)
        self.textEdit.setText('')
        QApplication.processEvents()  # обновляем интерфейс
        if not prompt:
            QMessageBox.warning(self.centralwidget, "Ошибка", "Введите текст!")
            return
        self.ai_thread.prompt_signal.emit(prompt)
        self.ai_thread.start()
        self.m_window.setWindowTitle('PyGPT - ' + prompt)


app = QtWidgets.QApplication(sys.argv)
MainWindow = QtWidgets.QMainWindow()
ui = Ui_MainWindow()
ui.setupUi(MainWindow)
MainWindow.show()
sys.exit(app.exec_())
